import type { Tool } from "@/types";
import {
  Calendar,
  CopyMinus,
  Layers,
  Scissors,
  Sparkles,
  Tag,
  ArrowLeftRight,
  Eraser,
  CaseLower,
  Replace,
  Edit3,
  Filter,
  ArrowUpDown,
  Download,
} from "lucide-react";

export const ICON_MAP = {
  Calendar,
  CopyMinus,
  Layers,
  Scissors,
  Sparkles,
  Tag,
  ArrowLeftRight,
  Eraser,
  CaseLower,
  Replace,
  Edit3,
  Filter,
  ArrowUpDown,
  Download,
} as const;

export type IconKey = keyof typeof ICON_MAP;

export const GENIE_TOOLS: Tool[] = [
  {
    id: "fix-dates",
    label: "Smart Date Fixer",
    description: "AI-driven normalization of inconsistent date formats across rows.",
    iconName: "Calendar",
    category: "Cleaning",
    contextType: "single-file",
    minPlan: "BASIC",
  },
  {
    id: "remove-duplicates",
    label: "Deduplication Engine",
    description: "Identify and remove redundant rows based on key columns.",
    iconName: "CopyMinus",
    category: "Cleaning",
    contextType: "single-file",
    minPlan: "PRO",
  },
  {
    id: "merge-datasets",
    label: "Deep Joiner",
    description: "Merge multiple CSV/Excel datasets using common keys.",
    iconName: "Layers",
    category: "Analytics",
    contextType: "multi-file",
    minPlan: "ADVANCE",
  },
  {
    id: "split-column",
    label: "Column Splitter",
    description: "Divide one column into multiple based on a delimiter or pattern.",
    iconName: "Scissors",
    category: "Cleaning",
    contextType: "single-file",
    minPlan: "BASIC",
  },
  {
    id: "smart-fill",
    label: "AI Smart Fill",
    description: "Predict and fill missing values using Genie's AI models.",
    iconName: "Sparkles",
    category: "Optimization",
    contextType: "single-file",
    minPlan: "PRO",
  },
  {
    id: "smart-tagging",
    label: "AI Smart Tagging",
    description: "Automatically classify rows into categories based on content.",
    iconName: "Tag",
    category: "Analytics",
    contextType: "single-file",
    minPlan: "ADVANCE",
  },
  {
    id: "data-type-converter",
    label: "Type Converter",
    description: "Convert column data types (text ↔ number, date ↔ string).",
    iconName: "ArrowLeftRight",
    category: "Cleaning",
    contextType: "single-file",
    minPlan: "BASIC",
  },
  {
    id: "whitespace-cleaner",
    label: "Whitespace Cleaner",
    description: "Strip leading, trailing, or excessive spaces from cells.",
    iconName: "Eraser",
    category: "Cleaning",
    contextType: "single-file",
    minPlan: "BASIC",
  },
  {
    id: "case-changer",
    label: "Case Formatter",
    description: "Convert text to UPPER, lower, or Proper case in selected columns.",
    iconName: "CaseLower",
    category: "Cleaning",
    contextType: "single-file",
    minPlan: "BASIC",
  },
  {
    id: "find-replace",
    label: "Find & Replace",
    description: "Search for specific values or patterns and replace them globally.",
    iconName: "Replace",
    category: "Cleaning",
    contextType: "single-file",
    minPlan: "PRO",
  },
  {
    id: "column-renamer",
    label: "Column Renamer",
    description: "Rename column headers across your dataset with ease.",
    iconName: "Edit3",
    category: "Cleaning",
    contextType: "single-file",
    minPlan: "BASIC",
  },
  {
    id: "filter-rows",
    label: "Row Filter",
    description: "Filter rows based on custom conditions to extract insights.",
    iconName: "Filter",
    category: "Analytics",
    contextType: "single-file",
    minPlan: "BASIC",
  },
  {
    id: "sort-data",
    label: "Data Sorter",
    description: "Sort rows by any column in ascending or descending order.",
    iconName: "ArrowUpDown",
    category: "Cleaning",
    contextType: "single-file",
    minPlan: "BASIC",
  },
  {
    id: "export-format",
    label: "Export & Format",
    description: "Export clean data to CSV, Excel, or JSON with just one click.",
    iconName: "Download",
    category: "Optimization",
    contextType: "project",
    minPlan: "PRO",
  },
];